INSERT INTO Features (Name) VALUES
( 'Klimaanlegg'),
  ( 'Elektriske Vinduer'),
  ( 'Foldbare Speil'),
  ( 'Krom Dørhåndtag'),
  ( 'Parkeringssensorer'),
  ( 'Navigasjonssystem'),
  ( 'Bluetooth-tilkobling'),
  ( 'Fartsholder'),
  ( 'Ryggekamera'),
  ('Lærseter'),
  ( 'Elektrisk Førersetejustering'),
  ( 'Lydsystem'),
  ( 'Soltak'),
  ( 'Airbags'),
  ('Filfølgeassistent'),
  ( 'Adaptiv Fartsholder'),
  ('Automatisk Kjøreassistansesystem'),
  ('Tretthetsvarslingssystem');